#!/usr/bin/env python3
"""Generate src/enum_names.rs from the rustyfit crate sources.

rustyfit's `profile::typedef` module contains ~200 generated newtype structs
(Sport, Event, ...) whose Display impl renders the FIT profile name of a value
("running") for known values and "TypeName(N)" for unknown ones. This script
generates a single dispatch function mapping (ProfileType, integer value) to
that Display rendering, so `fitfast.parse(..., enum_names=True)` can emit
human-readable enum names like the official Garmin SDKs do.

Usage:
    python scripts/gen_enum_names.py <path-to-rustyfit-crate-root>

The output is committed (src/enum_names.rs), so this script is only needed
when bumping the rustyfit dependency.
"""

import re
import sys
from pathlib import Path

# ProfileType variants that are primitive base types or handled specially
# (timestamps) rather than named enums.
SKIP = {
    "Enum", "Sint8", "Uint8", "Sint16", "Uint16", "Sint32", "Uint32",
    "String", "Float32", "Float64", "Uint8z", "Uint16z", "Uint32z",
    "Byte", "Sint64", "Uint64", "Uint64z",
    "DateTime", "LocalDateTime",  # converted to timestamps, not names
}


def main() -> None:
    crate = Path(sys.argv[1])
    profile_type_rs = (crate / "src/profile/profile_type.rs").read_text()
    typedef_dir = crate / "src/profile/typedef"

    m = re.search(r"pub enum ProfileType \{(.*?)\}", profile_type_rs, re.S)
    variants = re.findall(r"^\s*([A-Z]\w*),", m.group(1), re.M)

    # typedef type name -> inner integer type, e.g. Sport -> u8
    inner: dict[str, str] = {}
    for f in typedef_dir.glob("*.rs"):
        for name, ty in re.findall(
            r"pub struct (\w+)\(pub ([iu](?:8|16|32|64))\);", f.read_text()
        ):
            inner[name] = ty

    arms = []
    covered = 0
    for v in variants:
        if v in SKIP:
            continue
        if v not in inner:
            continue  # no typedef newtype for this variant; fall through to None
        arms.append(
            f"        ProfileType::{v} => named(typedef::{v}(v as {inner[v]})),"
        )
        covered += 1

    out = f"""\
// Generated by scripts/gen_enum_names.py from rustyfit's profile sources.
// DO NOT EDIT BY HAND. Regenerate when bumping the rustyfit dependency.
//
// Maps a (ProfileType, raw integer value) pair to the FIT profile name of
// that value ("running", "activity", ...). Returns None for unknown values
// and for profile types that are not named enums ({covered} covered).

use core::fmt::Display;
use rustyfit::profile::{{typedef, ProfileType}};

fn named<T: Display>(t: T) -> Option<String> {{
    let s = t.to_string();
    // typedef Display renders unknown values as "TypeName(N)"; profile names
    // themselves are snake_case identifiers and never contain '('.
    if s.contains('(') {{ None }} else {{ Some(s) }}
}}

#[allow(clippy::match_same_arms)]
pub fn enum_value_name(pt: ProfileType, v: i128) -> Option<String> {{
    match pt {{
{chr(10).join(arms)}
        _ => None,
    }}
}}
"""
    dest = Path(__file__).resolve().parent.parent / "src/enum_names.rs"
    dest.write_text(out)
    print(f"wrote {dest}: {covered} profile types covered")


if __name__ == "__main__":
    main()
